[theme]
primaryColor             = "#e8a520"
backgroundColor          = "#070604"
secondaryBackgroundColor = "#110e09"
textColor                = "#d4c4a0"
font                     = "monospace"

[client]
toolbarMode      = "viewer"
showErrorDetails = false

[server]
enableCORS           = false
enableXsrfProtection = true
